---
- name: CI Pipeline - Build & Push Docker Image to ECR
  hosts: docker_hosts
  become: yes

  vars_files:
    - ../../vault.yml

  roles:
    - docker
    - docker_build
    - aws_cli
    - aws_config
    - ecr_push

